# Generated by Django 4.1 on 2022-09-12 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Название товара"),
                ),
                ("description", models.TextField(verbose_name="Описание товара")),
                ("price", models.PositiveIntegerField(verbose_name="Цена товара")),
                ("image", models.ImageField(upload_to="images/")),
            ],
        ),
    ]
