# Generated by Django 4.1 on 2022-09-13 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stripe_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="currency",
            field=models.CharField(
                choices=[("USD", "usd"), ("RUB", "rub")], default="USD", max_length=9
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="image",
            field=models.ImageField(upload_to="products/"),
        ),
    ]
